### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by iliakan** [stapelberg/coronaqr#14]
I'm newbie to Go.

What should I install/setup before using instructions?

P.S. `apt-get install golang` and adding $GOPATH/$GOLANG wasn't enough.

```
root:~#  go get -u github.com/stapelberg/coronaqr/cmd/coronadecode
package context: unrecognized import path "context" (import path does not begin with hostname)
package flag: unrecognized import path "flag" (import path does not begin with hostname)
package fmt: unrecognized import path "fmt" (import path does not begin with hostname)
...
```

**Comment by stapelberg** [comment]
I suspect your version of Go is too old. Please follow https://go.dev/dl/ first.

**Comment by iliakan** [comment]
go version go1.7.4 linux/amd64 too old?

**Comment by stapelberg** [comment]
Definitely! That’s from 2016! https://en.wikipedia.org/wiki/Go_(programming_language)#Version_history

Use the current major version of Go (1.17).

**Comment by iliakan** [comment]
Well, that's Debian 9 version ;)

Did you try on Mac?

**Comment by iliakan** [comment]
I just tried it on Mac.

`go version go1.17.5 darwin/amd64`

Seems to work ;)
