### ISSUE TITLE
Fails to read EUDCC issued in Ireland

### ISSUE THREAD

**Issue by NightTsarina** [stapelberg/coronaqr#3]
Hi Michael!

Thanks for creating this, I received my certificate yesterday and I am eager to see what information is encoded there! Sadly, coronadecode (commit 4d67a18) fails to parse it:

```
$ zbarimg --quiet --raw ~/Covid_cert.png | bin/coronadecode
2021/07/15 16:11:55 could not decode certificate QR code: cbor.Unmarshal(v.Payload): cbor: cannot unmarshal primitives into Go struct field coronaqr.claims.-260 of type int
```

**Comment by NightTsarina** [comment]
If it is useful, I can give you the output of zbarimg in private.

**Comment by stapelberg** [comment]
Thanks for reporting this! 

There are a couple of example codes in https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/IE which all work, so I’m curious how your code differs.

Can you send me your zbarimg via email please?

**Comment by NightTsarina** [comment]
Done! (let me know if the email does not arrive)

**Comment by stapelberg** [comment]
Should be fixed now, thanks for sending the sample!
