### ISSUE TITLE
Consider adding support for the Swiss Light Certificates

### ISSUE THREAD

**Issue by stapelberg** [stapelberg/coronaqr#4]
I can’t find a spec, but here’s what I know so far:

Light certificates start with `LT1` instead of `HC1`.

The CBOR payload for light certificates is:

```{1: "CH BAG", 6: 1625658361, -250: {1: {"dob": "1943-02-01", "nam": {"fn": "M\u00fcller", "gn": "C\u00e9line", "fnt": "MUELLER", "gnt": "CELINE"}, "ver": "1.0.0"}}}```

Notably, the -250 is listed as unassigned in https://www.iana.org/assignments/cwt/cwt.xhtml currently :-/

**Comment by jvdassen** [comment]
Thanks for considering this.
Maybe the tests from the 'official' app can be used to obtain test data:
https://github.com/admin-ch/CovidCertificate-SDK-Kotlin/blob/main/src/test/java/ch/admin/bag/covidcertificate/sdk/core/TestData.kt#L18

Maybe close to a spec:
https://github.com/admin-ch/CovidCertificate-SDK-Kotlin/blob/main/src/main/java/ch/admin/bag/covidcertificate/sdk/core/decoder/CertificateDecoder.kt#L33-L53
https://github.com/admin-ch/CovidCertificate-SDK-Kotlin/blob/main/src/main/java/ch/admin/bag/covidcertificate/sdk/core/models/healthcert/light/ChLightCert.kt

**Comment by stapelberg** [comment]
Yep, that’s what I’ve been working with :)

The non-trivial part was getting the swiss trust list integrated.

Thanks for your pointers!
