### ISSUE TITLE
Output in machine readable format

### ISSUE THREAD

**Issue by WindowsNT** [stapelberg/coronaqr#9]
Is it possible to output in XML or JSON so it can be easily parsed?

Very nice tool.

**Comment by stapelberg** [comment]
No, the machine-readable interface is the Go API, see https://pkg.go.dev/github.com/stapelberg/coronaqr

If you need XML, JSON or something else entirely (from another language than Go), write a tiny Go program which uses the API and outputs what you need :)

The tricky bit is ensuring the verified data remains safe, i.e. avoiding unencrypted JSON being passed between machines or similar. I don’t want to come up with convoluted schemes for that, so I’m leaving any interface except for the Go API to the users who need them.
